var disa_udop_tracks__1_0_lib_Module_Factory = function () {
  var disa_udop_tracks__1_0_lib = {
    name: 'disa_udop_tracks__1_0_lib',
    defaultElementNamespaceURI: 'urn:disa:udop.tracks:1.0:lib',
    defaultAttributeNamespaceURI: 'http:\/\/release.niem.gov\/niem\/structures\/3.0\/',
    dependencies: ['NiemProxyXd_TrackInfo', 'NiemStructures_TrackInfo', 'disa_udop_tracks__1_0_genlib'],
    typeInfos: [{
        localName: 'EntityOverTheHorizonTrackNumberDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'commandName',
            required: true,
            elementName: 'CommandName',
            typeInfo: '.OTHTrackNumberCommandNameType'
          }, {
            name: 'trackNumberID',
            required: true,
            elementName: 'TrackNumberID',
            typeInfo: '.OTHTrackNumberTrackNumberIdentifierType'
          }]
      }, {
        localName: 'EntityUniqueIdentificationCodeDetailsType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityScopeCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.EntityScopeCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'MotionModelCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.MotionModelCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntitySystemTrackNumberDetailsType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityUniqueReferenceCodeDetailsType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Int',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'GeneralRemarksDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'remarkText',
            required: true,
            maxOccurs: 4,
            collection: true,
            elementName: 'RemarkText',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'commandText',
            attributeName: {
              localPart: 'commandText',
              namespaceURI: 'urn:disa:udop.tracks:1.0:lib'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EntityRelationshipFreeFormTextType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'LinkMode4IffIdentifierCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Int',
            values: [0, 1, 2, 3],
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityFlagCategoryType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'ForceStructureDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'echelonText',
            elementName: 'EchelonText',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'serviceText',
            elementName: 'ServiceText',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'adminOrgParentID',
            elementName: 'AdminOrgParentID',
            typeInfo: '.EntityUniqueIdentifierDetailsType'
          }, {
            name: 'taskOrgAffiliation',
            minOccurs: 0,
            collection: true,
            elementName: 'TaskOrgAffiliation',
            typeInfo: '.TaskOrgAffiliationDetailsType'
          }]
      }, {
        localName: 'EntityRelationshipVerifiedCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.EntityRelationshipVerifiedCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'TrademarkIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'SystemTrackNumberType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityNumberIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityNickNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'DataAmplificationDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'rawData',
            minOccurs: 0,
            collection: true,
            elementName: 'RawData',
            typeInfo: '.RawDataDetailsType'
          }]
      }, {
        localName: 'OriginatorType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'MIDBUnitIdType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'NetworkIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityClassNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'NetworkCategoryIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'NetworkNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityTrackDetailsType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Token',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'IFFDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'mode1',
            elementName: 'Mode1',
            typeInfo: 'disa_udop_tracks__1_0_genlib.Octal2DigitType'
          }, {
            name: 'mode2',
            elementName: 'Mode2',
            typeInfo: 'disa_udop_tracks__1_0_genlib.Octal4DigitType'
          }, {
            name: 'mode3',
            elementName: 'Mode3',
            typeInfo: 'disa_udop_tracks__1_0_genlib.Octal4DigitType'
          }, {
            name: 'mode4Code',
            elementName: 'Mode4Code',
            typeInfo: '.LinkMode4IffIdentifierCodeType'
          }]
      }, {
        localName: 'OTHTrackNumberTrackNumberIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'InternationalRadioCallSignIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityCategoryType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'RelationshipDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'relationship',
            required: true,
            elementName: 'Relationship',
            typeInfo: '.RelationshipDetailsType'
          }, {
            name: 'uid',
            required: true,
            collection: true,
            elementName: 'UID',
            typeInfo: '.EntityUniqueIdentifierDetailsType'
          }, {
            name: 'uniqueIdentificationText',
            required: true,
            collection: true,
            elementName: 'UniqueIdentificationText',
            typeInfo: '.EntityUniqueIdentificationCodeDetailsType'
          }, {
            name: 'uniqueReferenceText',
            required: true,
            collection: true,
            elementName: 'UniqueReferenceText',
            typeInfo: '.EntityUniqueReferenceCodeDetailsType'
          }, {
            name: 'othTrackNumber',
            required: true,
            collection: true,
            elementName: 'OTHTrackNumber',
            typeInfo: '.EntityOverTheHorizonTrackNumberDetailsType'
          }, {
            name: 'networkIdentifier',
            required: true,
            collection: true,
            elementName: 'NetworkIdentifier',
            typeInfo: '.NetworkIdentifierDetailsType'
          }]
      }, {
        localName: 'NetworkIdentifierDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'networkCategoryID',
            required: true,
            elementName: 'NetworkCategoryID',
            typeInfo: '.IdentifierType'
          }, {
            name: 'networkName',
            elementName: 'NetworkName',
            typeInfo: '.NetworkNameType'
          }, {
            name: 'networkID',
            required: true,
            elementName: 'NetworkID',
            typeInfo: '.NetworkIdentifierType'
          }]
      }, {
        localName: 'EntityUniqueIdentifierDetailsType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'TaskOrgAffiliationDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'taskOrgName',
            elementName: 'TaskOrgName',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'taskOrgNumberText',
            elementName: 'TaskOrgNumberText',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'taskOrgParentID',
            elementName: 'TaskOrgParentID',
            typeInfo: '.EntityUniqueIdentifierDetailsType'
          }]
      }, {
        localName: 'IdentifierType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'networkCategoryVerifiedIdentifierCode',
            required: true,
            elementName: 'NetworkCategoryVerifiedIdentifierCode',
            typeInfo: '.NetworkCategoryVerifiedIdentifierCodeType'
          }, {
            name: 'networkCategoryIdentifierID',
            required: true,
            elementName: 'NetworkCategoryIdentifierID',
            typeInfo: '.NetworkCategoryIdentifierType'
          }]
      }, {
        localName: 'AlertCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.AlertCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityTacticalTrainingCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.EntityTacticalTrainingCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityRelationshipType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'entityRelationshipVerifiedCode',
            required: true,
            elementName: 'EntityRelationshipVerifiedCode',
            typeInfo: '.EntityRelationshipVerifiedCodeType'
          }, {
            name: 'entityRelationshipFreeFormText',
            required: true,
            elementName: 'EntityRelationshipFreeFormText',
            typeInfo: '.EntityRelationshipFreeFormTextType'
          }]
      }, {
        localName: 'ShipControlNumberIdentifierType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'OTHTrackNumberCommandNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'RawDataDetailsType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'dataCategoryText',
            elementName: 'DataCategoryText',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }, {
            name: 'dataText',
            elementName: 'DataText',
            typeInfo: 'NiemProxyXd_TrackInfo.Base64Binary'
          }]
      }, {
        localName: 'NetworkCategoryVerifiedIdentifierCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.NetworkCategoryVerifiedIdentifierCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'NetworkCategoryVerifiedIdentifierCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['ACDS', 'CEC', 'CSEL', 'CSI', 'LatteralTell', 'Link11', 'Link14', 'Link16', 'FCS', 'Spa25']
      }, {
        type: 'enumInfo',
        localName: 'EntityTacticalTrainingCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['Tactical', 'Live Training', 'Simulated Training', 'Transposed']
      }, {
        type: 'enumInfo',
        localName: 'EntityScopeCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['Over the Horizon', 'Local', 'Terminal']
      }, {
        type: 'enumInfo',
        localName: 'EntityRelationshipVerifiedCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['Subcomponent of', 'Contains subcomponent(s)', 'Embarked on', 'Contains embarked', 'Subcomponent of plan(s)', 'Engaged by', 'Engaging', 'Member of', 'Reporting Unit', 'Controlling Unit', 'Time Critical Target for plan', 'Fire', 'Investigate', 'Track', 'Associate', 'Correlate']
      }, {
        type: 'enumInfo',
        localName: 'MotionModelCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['Barrier', 'Patrol', 'Transit', 'Dead In Water', 'Unknown', 'Land Site', 'Air Contact']
      }, {
        type: 'enumInfo',
        localName: 'AlertCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['TGT', 'SUS', 'HIT', 'NSP']
      }],
    elementInfos: [{
        typeInfo: '.NetworkCategoryVerifiedIdentifierCodeType',
        elementName: 'NetworkCategoryVerifiedIdentifierCode'
      }, {
        typeInfo: '.NetworkIdentifierType',
        elementName: 'NetworkID'
      }, {
        typeInfo: '.MIDBUnitIdType',
        elementName: 'MIDBUnitID'
      }, {
        typeInfo: '.NetworkNameType',
        elementName: 'NetworkName'
      }, {
        typeInfo: '.EntityUniqueIdentificationCodeDetailsType',
        elementName: 'UnitIdentificationCode'
      }, {
        typeInfo: '.RawDataDetailsType',
        elementName: 'RawData'
      }, {
        typeInfo: 'disa_udop_tracks__1_0_genlib.Octal4DigitType',
        elementName: 'Mode3'
      }, {
        typeInfo: '.EntityUniqueReferenceCodeDetailsType',
        elementName: 'UniqueReferenceText'
      }, {
        typeInfo: '.EntityClassNameType',
        elementName: 'EntityClassName'
      }, {
        typeInfo: '.NetworkIdentifierDetailsType',
        elementName: 'NetworkIdentifier'
      }, {
        typeInfo: '.OriginatorType',
        elementName: 'OriginatorText'
      }, {
        typeInfo: '.TaskOrgAffiliationDetailsType',
        elementName: 'TaskOrgAffiliation'
      }, {
        typeInfo: 'disa_udop_tracks__1_0_genlib.Octal4DigitType',
        elementName: 'Mode2'
      }, {
        typeInfo: '.EntityUniqueIdentificationCodeDetailsType',
        elementName: 'UniqueIdentificationText'
      }, {
        typeInfo: '.IdentifierType',
        elementName: 'NetworkCategoryID'
      }, {
        typeInfo: '.EntityUniqueIdentifierDetailsType',
        elementName: 'UID'
      }, {
        typeInfo: '.EntityOverTheHorizonTrackNumberDetailsType',
        elementName: 'OTHTrackNumber'
      }, {
        typeInfo: '.EntityUniqueIdentifierDetailsType',
        elementName: 'TaskOrgParentID'
      }, {
        typeInfo: '.EntityNumberIdentifierType',
        elementName: 'EntityNumberID'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'RemarkText'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'OriginatorKeyText'
      }, {
        typeInfo: '.DataAmplificationDetailsType',
        elementName: 'DataAmplification'
      }, {
        typeInfo: '.OTHTrackNumberCommandNameType',
        elementName: 'CommandName'
      }, {
        typeInfo: '.NetworkCategoryIdentifierType',
        elementName: 'NetworkCategoryIdentifierID'
      }, {
        typeInfo: '.LinkMode4IffIdentifierCodeType',
        elementName: 'Mode4Code'
      }, {
        typeInfo: '.AlertCodeType',
        elementName: 'AlertCode'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'EchelonText'
      }, {
        typeInfo: '.EntityUniqueIdentifierDetailsType',
        elementName: 'AdminOrgParentID'
      }, {
        typeInfo: '.OTHTrackNumberTrackNumberIdentifierType',
        elementName: 'TrackNumberID'
      }, {
        typeInfo: '.RelationshipDetailsType',
        elementName: 'Relationship'
      }, {
        typeInfo: '.MotionModelCodeType',
        elementName: 'MotionModelCode'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'ServiceText'
      }, {
        typeInfo: '.EntityRelationshipVerifiedCodeType',
        elementName: 'EntityRelationshipVerifiedCode'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.Base64Binary',
        elementName: 'DataText'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'TaskOrgName'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'DataCategoryText'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'TaskOrgNumberText'
      }, {
        typeInfo: 'disa_udop_tracks__1_0_genlib.Octal2DigitType',
        elementName: 'Mode1'
      }, {
        typeInfo: '.IFFDetailsType',
        elementName: 'IFF'
      }, {
        typeInfo: '.EntityRelationshipFreeFormTextType',
        elementName: 'EntityRelationshipFreeFormText'
      }]
  };
  return {
    disa_udop_tracks__1_0_lib: disa_udop_tracks__1_0_lib
  };
};
if (typeof define === 'function' && define.amd) {
  define([], disa_udop_tracks__1_0_lib_Module_Factory);
}
else {
  var disa_udop_tracks__1_0_lib_Module = disa_udop_tracks__1_0_lib_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.disa_udop_tracks__1_0_lib = disa_udop_tracks__1_0_lib_Module.disa_udop_tracks__1_0_lib;
  }
  else {
    var disa_udop_tracks__1_0_lib = disa_udop_tracks__1_0_lib_Module.disa_udop_tracks__1_0_lib;
  }
}