var NIEM_Core_Module_Factory = function () {
  var NIEM_Core = {
    name: 'NIEM_Core',
    defaultElementNamespaceURI: 'http:\/\/release.niem.gov\/niem\/niem-core\/3.0\/',
    defaultAttributeNamespaceURI: 'http:\/\/release.niem.gov\/niem\/structures\/3.0\/',
    dependencies: ['gov_niem_release_niem_structures__3', 'gov_niem_release_niem_proxy_xsd__3', 'gov_niem_release_niem_codes_nga_datum__3', 'gov_niem_release_niem_codes_unece_rec20__3'],
    typeInfos: [{
        localName: 'JurisdictionType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'locationCountry',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'LocationCountry',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'LatitudeDegreeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'LongitudeDegreeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'LongitudeCoordinateType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'longitudeDegreeValue',
            elementName: 'LongitudeDegreeValue',
            typeInfo: '.LongitudeDegreeType'
          }]
      }, {
        localName: 'StatusType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'statusCommentText',
            minOccurs: 0,
            collection: true,
            elementName: 'StatusCommentText',
            typeInfo: '.TextType'
          }]
      }, {
        localName: 'DirectionCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.DirectionCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'EntityType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'entityRepresentation',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'EntityRepresentation',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'DateType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'dateRepresentation',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'DateRepresentation',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'PersonType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'personDescriptionText',
            minOccurs: 0,
            collection: true,
            elementName: 'PersonDescriptionText',
            typeInfo: '.TextType'
          }, {
            name: 'personName',
            minOccurs: 0,
            collection: true,
            elementName: 'PersonName',
            typeInfo: '.PersonNameType'
          }, {
            name: 'personAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'PersonAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'IdentificationType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'identificationID',
            minOccurs: 0,
            collection: true,
            elementName: 'IdentificationID',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String'
          }, {
            name: 'identificationJurisdiction',
            minOccurs: 0,
            collection: true,
            elementName: 'IdentificationJurisdiction',
            typeInfo: '.JurisdictionType'
          }, {
            name: 'identificationAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'IdentificationAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'PersonNameType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'personFullName',
            minOccurs: 0,
            collection: true,
            elementName: 'PersonFullName',
            typeInfo: '.PersonNameTextType'
          }]
      }, {
        localName: 'AngularMinuteType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'TelephoneNumberType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'ItemType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'InstantMessengerType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'instantMessengerServiceName',
            minOccurs: 0,
            collection: true,
            elementName: 'InstantMessengerServiceName',
            typeInfo: '.TextType'
          }, {
            name: 'instantMessengerScreenID',
            minOccurs: 0,
            collection: true,
            elementName: 'InstantMessengerScreenID',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String'
          }]
      }, {
        localName: 'AngularSecondType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'FullTelephoneNumberType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'telephoneNumberFullID',
            minOccurs: 0,
            collection: true,
            elementName: 'TelephoneNumberFullID',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String'
          }, {
            name: 'telephoneSuffixID',
            minOccurs: 0,
            collection: true,
            elementName: 'TelephoneSuffixID',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String'
          }, {
            name: 'fullTelephoneNumberAugmentationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'FullTelephoneNumberAugmentationPoint',
            typeInfo: 'AnyType'
          }]
      }, {
        localName: 'FacilityType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'facilityIdentification',
            minOccurs: 0,
            collection: true,
            elementName: 'FacilityIdentification',
            typeInfo: '.IdentificationType'
          }, {
            name: 'facilityName',
            minOccurs: 0,
            collection: true,
            elementName: 'FacilityName',
            typeInfo: '.ProperNameTextType'
          }, {
            name: 'facilityAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'FacilityAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'OrganizationType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'organizationAbbreviationText',
            minOccurs: 0,
            collection: true,
            elementName: 'OrganizationAbbreviationText',
            typeInfo: '.TextType'
          }, {
            name: 'organizationName',
            minOccurs: 0,
            collection: true,
            elementName: 'OrganizationName',
            typeInfo: '.TextType'
          }]
      }, {
        localName: 'ContactRadioType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'contactRadioChannelText',
            minOccurs: 0,
            collection: true,
            elementName: 'ContactRadioChannelText',
            typeInfo: '.TextType'
          }, {
            name: 'contactRadioCallSignID',
            minOccurs: 0,
            collection: true,
            elementName: 'ContactRadioCallSignID',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String'
          }]
      }, {
        localName: 'MeasureType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'measureValue',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'MeasureValue',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'measureUnit',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'MeasureUnit',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'LocationHeightMeasureType',
        baseTypeInfo: '.MeasureType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'locationHeightVerticalDatum',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'LocationHeightVerticalDatum',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'TextType',
        baseTypeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'Location2DGeospatialCoordinateType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'geographicCoordinateLatitude',
            required: true,
            elementName: 'GeographicCoordinateLatitude',
            typeInfo: '.LatitudeCoordinateType'
          }, {
            name: 'geographicCoordinateLongitude',
            required: true,
            elementName: 'GeographicCoordinateLongitude',
            typeInfo: '.LongitudeCoordinateType'
          }, {
            name: 'location2DGeospatialCoordinateAugmentationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'Location2DGeospatialCoordinateAugmentationPoint',
            typeInfo: 'AnyType'
          }]
      }, {
        localName: 'PersonNameTextType',
        baseTypeInfo: '.ProperNameTextType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'DateRangeType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'startDate',
            minOccurs: 0,
            collection: true,
            elementName: 'StartDate',
            typeInfo: '.DateType'
          }, {
            name: 'endDate',
            minOccurs: 0,
            collection: true,
            elementName: 'EndDate',
            typeInfo: '.DateType'
          }]
      }, {
        localName: 'Location3DGeospatialCoordinateType',
        baseTypeInfo: '.Location2DGeospatialCoordinateType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'locationHeight',
            required: true,
            mixed: false,
            allowDom: false,
            elementName: 'LocationHeight',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'AngularMeasureType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'angularDegreeValue',
            minOccurs: 0,
            collection: true,
            elementName: 'AngularDegreeValue',
            typeInfo: 'gov_niem_release_niem_proxy_xsd__3.Integer'
          }, {
            name: 'angularMinuteValue',
            minOccurs: 0,
            collection: true,
            elementName: 'AngularMinuteValue',
            typeInfo: '.AngularMinuteType'
          }, {
            name: 'angularSecondValue',
            minOccurs: 0,
            collection: true,
            elementName: 'AngularSecondValue',
            typeInfo: '.AngularSecondType'
          }, {
            name: 'angularMeasureAugmentationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'AngularMeasureAugmentationPoint',
            typeInfo: 'AnyType'
          }]
      }, {
        localName: 'Degree360Type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'LocationType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'locationGeospatialCoordinate',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'LocationGeospatialCoordinate',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'locationAugmentationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'LocationAugmentationPoint',
            typeInfo: 'AnyType'
          }]
      }, {
        localName: 'ProperNameTextType',
        baseTypeInfo: '.TextType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'LatitudeCoordinateType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'latitudeDegreeValue',
            elementName: 'LatitudeDegreeValue',
            typeInfo: '.LatitudeDegreeType'
          }]
      }, {
        localName: 'SystemIdentificationType',
        baseTypeInfo: '.IdentificationType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'systemName',
            minOccurs: 0,
            collection: true,
            elementName: 'SystemName',
            typeInfo: '.TextType'
          }, {
            name: 'systemIdentificationAugmentationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'SystemIdentificationAugmentationPoint',
            typeInfo: 'AnyType'
          }]
      }, {
        localName: 'ContactInformationType',
        baseTypeInfo: 'gov_niem_release_niem_structures__3.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'contactMeans',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'ContactMeans',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'contactEntity',
            minOccurs: 0,
            collection: true,
            elementName: 'ContactEntity',
            typeInfo: '.EntityType'
          }, {
            name: 'contactInformationAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'ContactInformationAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        type: 'enumInfo',
        localName: 'DirectionCodeSimpleType',
        values: ['E', 'ENE', 'ESE', 'N', 'NE', 'NNE', 'NNW', 'NW', 'S', 'SE', 'SSE', 'SSW', 'SW', 'W', 'WNW', 'WSW']
      }],
    elementInfos: [{
        typeInfo: 'AnyType',
        elementName: 'AngularMeasureAugmentationPoint'
      }, {
        typeInfo: '.InstantMessengerType',
        elementName: 'ContactInstantMessenger',
        substitutionHead: 'ContactMeans'
      }, {
        typeInfo: '.Location3DGeospatialCoordinateType',
        elementName: 'Location3DGeospatialCoordinate',
        substitutionHead: 'LocationGeospatialCoordinate'
      }, {
        typeInfo: '.LongitudeDegreeType',
        elementName: 'LongitudeDegreeValue'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'InstantMessengerScreenID'
      }, {
        typeInfo: '.DateType',
        elementName: 'StartDate'
      }, {
        typeInfo: '.ProperNameTextType',
        elementName: 'LocationCountryName',
        substitutionHead: 'LocationCountry'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'IdentificationID'
      }, {
        typeInfo: '.LongitudeCoordinateType',
        elementName: 'GeographicCoordinateLongitude'
      }, {
        typeInfo: '.StatusType',
        elementName: 'Status'
      }, {
        typeInfo: '.TelephoneNumberType',
        elementName: 'ContactTelephoneNumber',
        substitutionHead: 'ContactMeans'
      }, {
        typeInfo: 'gov_niem_release_niem_codes_nga_datum__3.VerticalDatumCodeType',
        elementName: 'LocationHeightVerticalDatumCode',
        substitutionHead: 'LocationHeightVerticalDatum'
      }, {
        typeInfo: 'AnyType',
        elementName: 'FacilityAugmentationPoint'
      }, {
        typeInfo: '.DateType',
        elementName: 'EndDate'
      }, {
        typeInfo: '.LatitudeDegreeType',
        elementName: 'LatitudeDegreeValue'
      }, {
        typeInfo: '.LocationHeightMeasureType',
        elementName: 'LocationElevation',
        substitutionHead: 'LocationHeight'
      }, {
        typeInfo: '.ProperNameTextType',
        elementName: 'FacilityName'
      }, {
        typeInfo: 'AnyType',
        elementName: 'MeasurePoint',
        substitutionHead: 'MeasureValue'
      }, {
        typeInfo: 'AnyType',
        elementName: 'LocationHeight'
      }, {
        typeInfo: 'AnyType',
        elementName: 'ContactInformationAugmentationPoint'
      }, {
        typeInfo: '.PersonType',
        elementName: 'Person'
      }, {
        typeInfo: '.TextType',
        elementName: 'LocationHeightVerticalDatumText',
        substitutionHead: 'LocationHeightVerticalDatum'
      }, {
        typeInfo: 'AnyType',
        elementName: 'EntityRepresentation'
      }, {
        typeInfo: '.PersonNameType',
        elementName: 'PersonName'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'TelephoneSuffixID'
      }, {
        typeInfo: 'AnyType',
        elementName: 'Contact'
      }, {
        typeInfo: '.IdentificationType',
        elementName: 'Identification'
      }, {
        typeInfo: '.TextType',
        elementName: 'ContactRadioChannelText'
      }, {
        typeInfo: 'AnyType',
        elementName: 'MeasureUnit'
      }, {
        typeInfo: 'AnyType',
        elementName: 'LocationAugmentationPoint'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'ContactRadioCallSignID'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.DateTime',
        elementName: 'DateTime',
        substitutionHead: 'DateRepresentation'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.Integer',
        elementName: 'AngularDegreeValue'
      }, {
        typeInfo: 'AnyType',
        elementName: 'LocationCountry'
      }, {
        typeInfo: 'AnyType',
        elementName: 'PersonAugmentationPoint'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.Integer',
        elementName: 'MeasureIntegerValue',
        substitutionHead: 'MeasurePoint'
      }, {
        typeInfo: '.PersonType',
        elementName: 'EntityPerson',
        substitutionHead: 'EntityRepresentation'
      }, {
        typeInfo: 'AnyType',
        elementName: 'Location2DGeospatialCoordinateAugmentationPoint'
      }, {
        typeInfo: '.IdentificationType',
        elementName: 'FacilityIdentification'
      }, {
        typeInfo: '.AngularMinuteType',
        elementName: 'AngularMinuteValue'
      }, {
        typeInfo: '.ContactInformationType',
        elementName: 'ContactInformation'
      }, {
        typeInfo: 'AnyType',
        elementName: 'LocationHeightVerticalDatum'
      }, {
        typeInfo: '.LatitudeCoordinateType',
        elementName: 'GeographicCoordinateLatitude'
      }, {
        typeInfo: '.JurisdictionType',
        elementName: 'IdentificationJurisdiction'
      }, {
        typeInfo: '.TextType',
        elementName: 'StatusCommentText'
      }, {
        typeInfo: 'AnyType',
        elementName: 'IdentificationAugmentationPoint'
      }, {
        typeInfo: '.ContactRadioType',
        elementName: 'ContactRadio',
        substitutionHead: 'ContactMeans'
      }, {
        typeInfo: '.OrganizationType',
        elementName: 'EntityOrganization',
        substitutionHead: 'EntityRepresentation'
      }, {
        typeInfo: 'AnyType',
        elementName: 'SystemIdentificationAugmentationPoint'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.AnyURI',
        elementName: 'BinaryURI'
      }, {
        typeInfo: '.Location2DGeospatialCoordinateType',
        elementName: 'Location2DGeospatialCoordinate',
        substitutionHead: 'LocationGeospatialCoordinate'
      }, {
        typeInfo: '.EntityType',
        elementName: 'ContactEntity',
        substitutionHead: 'Contact'
      }, {
        typeInfo: '.TextType',
        elementName: 'InstantMessengerServiceName'
      }, {
        typeInfo: '.TextType',
        elementName: 'SystemName'
      }, {
        typeInfo: 'AnyType',
        elementName: 'ContactMeans'
      }, {
        typeInfo: 'AnyType',
        elementName: 'DateRepresentation'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'TelephoneNumberFullID'
      }, {
        typeInfo: '.FacilityType',
        elementName: 'Facility'
      }, {
        typeInfo: 'AnyType',
        elementName: 'MeasureValue'
      }, {
        typeInfo: '.TextType',
        elementName: 'OrganizationName'
      }, {
        typeInfo: 'AnyType',
        elementName: 'FullTelephoneNumberAugmentationPoint'
      }, {
        typeInfo: 'AnyType',
        elementName: 'LocationGeospatialCoordinate'
      }, {
        typeInfo: '.TextType',
        elementName: 'PersonDescriptionText'
      }, {
        typeInfo: '.PersonNameTextType',
        elementName: 'PersonFullName'
      }, {
        typeInfo: '.TextType',
        elementName: 'OrganizationAbbreviationText'
      }, {
        typeInfo: '.AngularSecondType',
        elementName: 'AngularSecondValue'
      }, {
        typeInfo: 'gov_niem_release_niem_codes_unece_rec20__3.LengthCodeType',
        elementName: 'LengthUnitCode',
        substitutionHead: 'MeasureUnit'
      }, {
        typeInfo: 'gov_niem_release_niem_proxy_xsd__3.String',
        elementName: 'ContactEmailID',
        substitutionHead: 'ContactMeans'
      }]
  };
  return {
    NIEM_Core: NIEM_Core
  };
};
if (typeof define === 'function' && define.amd) {
  define([], NIEM_Core_Module_Factory);
}
else {
  var NIEM_Core_Module = NIEM_Core_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.NIEM_Core = NIEM_Core_Module.NIEM_Core;
  }
  else {
    var NIEM_Core = NIEM_Core_Module.NIEM_Core;
  }
}