var NiemMilitaryoperations_TrackInfo_Module_Factory = function () {
  var NiemMilitaryoperations_TrackInfo = {
    name: 'NiemMilitaryoperations_TrackInfo',
    defaultElementNamespaceURI: 'http:\/\/release.niem.gov\/niem\/domains\/militaryOperations\/3.2\/',
    defaultAttributeNamespaceURI: 'http:\/\/release.niem.gov\/niem\/structures\/3.0\/',
    dependencies: ['net_opengis_gml_v_3_2_1', 'NiemCore_TrackInfo', 'gov_niem_release_niem_codes_nga_datum__3', 'NiemStructures_TrackInfo', 'NiemProxyXd_TrackInfo'],
    typeInfos: [{
        localName: 'MotionType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'courseAbstract',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'CourseAbstract',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'speedValue',
            minOccurs: 0,
            collection: true,
            elementName: 'SpeedValue',
            typeInfo: '.SpeedValueType'
          }]
      }, {
        localName: 'WGS84LocationCylinderType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'wgs84LocationPoint',
            minOccurs: 0,
            collection: true,
            elementName: 'WGS84LocationPoint',
            typeInfo: '.WGS84LocationPointType'
          }]
      }, {
        localName: 'UnitShortNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'UnitType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'unitName',
            minOccurs: 0,
            collection: true,
            elementName: 'UnitName',
            typeInfo: '.UnitNameType'
          }, {
            name: 'unitShortName',
            minOccurs: 0,
            collection: true,
            elementName: 'UnitShortName',
            typeInfo: '.UnitShortNameType'
          }, {
            name: 'unitTypeCodeText',
            minOccurs: 0,
            collection: true,
            elementName: 'UnitTypeCodeText',
            typeInfo: '.UnitTypeCodeTextType'
          }, {
            name: 'unitAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'UnitAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'Degree360Type',
        baseTypeInfo: 'NiemCore_TrackInfo.Degree360Type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'sigmaErrorValue',
            typeInfo: 'Decimal',
            attributeName: {
              localPart: 'sigmaErrorValue',
              namespaceURI: 'http:\/\/release.niem.gov\/niem\/domains\/militaryOperations\/3.2\/'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'UnitTypeCodeTextType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Token',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'SensorType',
        baseTypeInfo: 'NiemCore_TrackInfo.ItemType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'sensorIdentification',
            minOccurs: 0,
            collection: true,
            elementName: 'SensorIdentification',
            typeInfo: 'NiemCore_TrackInfo.IdentificationType'
          }]
      }, {
        localName: 'StandardIdentityCodeType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: '.StandardIdentityCodeSimpleType',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'MILSTD2525CSIDCType',
        typeName: 'MILSTD2525-C-SIDC-Type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Token',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'SpeedValueType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Decimal',
            type: 'value'
          }, {
            name: 'speedUnitCode',
            typeInfo: 'Token',
            attributeName: {
              localPart: 'speedUnitCode',
              namespaceURI: 'http:\/\/release.niem.gov\/niem\/domains\/militaryOperations\/3.2\/'
            },
            type: 'attribute'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'MissionType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'missionName',
            minOccurs: 0,
            collection: true,
            elementName: 'MissionName',
            typeInfo: 'NiemProxyXd_TrackInfo.String'
          }]
      }, {
        localName: 'UnitNameType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'value',
            typeInfo: 'Token',
            type: 'value'
          }, {
            name: 'id',
            typeInfo: 'ID',
            type: 'attribute'
          }, {
            name: 'ref',
            typeInfo: 'IDREF',
            type: 'attribute'
          }, {
            name: 'metadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }, {
            name: 'relationshipMetadata',
            typeInfo: 'IDREFS',
            type: 'attribute'
          }]
      }, {
        localName: 'CourseAngleDegreesMeasureType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'angleDegreesMeasure',
            minOccurs: 0,
            collection: true,
            elementName: 'AngleDegreesMeasure',
            typeInfo: 'NiemCore_TrackInfo.AngularMeasureType'
          }, {
            name: 'directionDatumAbstract',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'DirectionDatumAbstract',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'courseAngleDegreesMeasureAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'CourseAngleDegreesMeasureAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'EventType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'eventLocation',
            minOccurs: 0,
            collection: true,
            elementName: 'EventLocation',
            typeInfo: 'NiemCore_TrackInfo.LocationType'
          }, {
            name: 'eventIdentification',
            minOccurs: 0,
            collection: true,
            elementName: 'EventIdentification',
            typeInfo: 'NiemCore_TrackInfo.IdentificationType'
          }, {
            name: 'eventValidityDateTimeRange',
            minOccurs: 0,
            collection: true,
            elementName: 'EventValidityDateTimeRange',
            typeInfo: 'NiemCore_TrackInfo.DateRangeType'
          }, {
            name: 'eventMotion',
            minOccurs: 0,
            collection: true,
            elementName: 'EventMotion',
            typeInfo: '.MotionType'
          }, {
            name: 'eventAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'EventAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'TrackType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'trackIdentification',
            minOccurs: 0,
            collection: true,
            elementName: 'TrackIdentification',
            typeInfo: 'NiemCore_TrackInfo.IdentificationType'
          }, {
            name: 'trackAugmentationPoint',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementName: 'TrackAugmentationPoint',
            typeInfo: 'AnyType',
            type: 'elementRef'
          }]
      }, {
        localName: 'WGS84LocationPointType',
        baseTypeInfo: 'NiemStructures_TrackInfo.ObjectType',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'point',
            minOccurs: 0,
            collection: true,
            elementName: {
              localPart: 'Point',
              namespaceURI: 'http:\/\/www.opengis.net\/gml\/3.2'
            },
            typeInfo: 'net_opengis_gml_v_3_2_1.PointType'
          }]
      }, {
        type: 'enumInfo',
        localName: 'StandardIdentityCodeSimpleType',
        baseTypeInfo: 'Token',
        values: ['ASSUMED FRIEND', 'FAKER', 'FRIEND', 'HOSTILE', 'JOKER', 'NEUTRAL', 'SUSPECT', 'UNKNOWN']
      }],
    elementInfos: [{
        typeInfo: '.MotionType',
        elementName: 'EventMotion'
      }, {
        typeInfo: '.WGS84LocationPointType',
        elementName: 'WGS84LocationPoint'
      }, {
        typeInfo: 'AnyType',
        elementName: 'TrackAugmentationPoint'
      }, {
        typeInfo: '.UnitTypeCodeTextType',
        elementName: 'UnitTypeCodeText'
      }, {
        typeInfo: '.SensorType',
        elementName: 'Sensor'
      }, {
        typeInfo: '.Degree360Type',
        elementName: 'CourseValue',
        substitutionHead: 'CourseAbstract'
      }, {
        typeInfo: '.UnitType',
        elementName: 'Unit'
      }, {
        typeInfo: '.MissionType',
        elementName: 'Mission'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.Decimal',
        elementName: 'AngularMeasureDecimalValue',
        substitutionHead: 'CourseAngleDegreesMeasureAugmentationPoint'
      }, {
        typeInfo: 'AnyType',
        elementName: 'EventAugmentationPoint'
      }, {
        typeInfo: '.MILSTD2525CSIDCType',
        elementName: 'MILSTD2525-C-SIDC-Code'
      }, {
        typeInfo: 'AnyType',
        elementName: 'DirectionDatumAbstract'
      }, {
        typeInfo: '.WGS84LocationCylinderType',
        elementName: 'WGS84LocationCylinder',
        substitutionHead: {
          localPart: 'LocationGeospatialCoordinate',
          namespaceURI: 'http:\/\/release.niem.gov\/niem\/niem-core\/3.0\/'
        }
      }, {
        typeInfo: 'NiemCore_TrackInfo.AngularMeasureType',
        elementName: 'CourseAngleMeasure',
        substitutionHead: 'CourseAbstract'
      }, {
        typeInfo: 'NiemCore_TrackInfo.IdentificationType',
        elementName: 'EventIdentification'
      }, {
        typeInfo: 'NiemCore_TrackInfo.LocationType',
        elementName: 'EventLocation'
      }, {
        typeInfo: '.UnitNameType',
        elementName: 'UnitName'
      }, {
        typeInfo: 'NiemCore_TrackInfo.AngularMeasureType',
        elementName: 'AngleDegreesMeasure'
      }, {
        typeInfo: '.UnitShortNameType',
        elementName: 'UnitShortName'
      }, {
        typeInfo: 'AnyType',
        elementName: 'UnitAugmentationPoint'
      }, {
        typeInfo: '.TrackType',
        elementName: 'Track'
      }, {
        typeInfo: '.SpeedValueType',
        elementName: 'SpeedValue'
      }, {
        typeInfo: '.CourseAngleDegreesMeasureType',
        elementName: 'CourseAngleDegreesMeasure',
        substitutionHead: 'CourseAbstract'
      }, {
        typeInfo: 'AnyType',
        elementName: 'CourseAngleDegreesMeasureAugmentationPoint'
      }, {
        typeInfo: 'AnyType',
        elementName: 'CourseAbstract'
      }, {
        typeInfo: 'NiemCore_TrackInfo.IdentificationType',
        elementName: 'TrackIdentification'
      }, {
        typeInfo: 'NiemCore_TrackInfo.DirectionCodeType',
        elementName: 'CourseCode',
        substitutionHead: 'CourseAbstract'
      }, {
        typeInfo: 'NiemCore_TrackInfo.DateRangeType',
        elementName: 'EventValidityDateTimeRange'
      }, {
        typeInfo: 'gov_niem_release_niem_codes_nga_datum__3.DirectionDatumCodeType',
        elementName: 'DirectionDatumCode',
        substitutionHead: 'DirectionDatumAbstract'
      }, {
        typeInfo: 'NiemProxyXd_TrackInfo.String',
        elementName: 'MissionName'
      }, {
        typeInfo: '.EventType',
        elementName: 'Event'
      }, {
        typeInfo: 'NiemCore_TrackInfo.IdentificationType',
        elementName: 'SensorIdentification'
      }]
  };
  return {
    NiemMilitaryoperations_TrackInfo: NiemMilitaryoperations_TrackInfo
  };
};
if (typeof define === 'function' && define.amd) {
  define([], NiemMilitaryoperations_TrackInfo_Module_Factory);
}
else {
  var NiemMilitaryoperations_TrackInfo_Module = NiemMilitaryoperations_TrackInfo_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.NiemMilitaryoperations_TrackInfo = NiemMilitaryoperations_TrackInfo_Module.NiemMilitaryoperations_TrackInfo;
  }
  else {
    var NiemMilitaryoperations_TrackInfo = NiemMilitaryoperations_TrackInfo_Module.NiemMilitaryoperations_TrackInfo;
  }
}